[2024-10-22T02:05:24.091+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-22T02:05:24.105+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: auto_training_crawling_data_okx.crawl_data_task manual__2024-10-22T02:00:07.708586+00:00 [queued]>
[2024-10-22T02:05:24.112+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: auto_training_crawling_data_okx.crawl_data_task manual__2024-10-22T02:00:07.708586+00:00 [queued]>
[2024-10-22T02:05:24.113+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2024-10-22T02:05:24.132+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): crawl_data_task> on 2024-10-22 02:00:07.708586+00:00
[2024-10-22T02:05:24.145+0000] {standard_task_runner.py:72} INFO - Started process 365263 to run task
[2024-10-22T02:05:24.154+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'auto_training_crawling_data_okx', 'crawl_data_task', 'manual__2024-10-22T02:00:07.708586+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/full_pipeline.py', '--cfg-path', '/tmp/tmpdlh_ah7t']
[2024-10-22T02:05:24.157+0000] {standard_task_runner.py:105} INFO - Job 39: Subtask crawl_data_task
[2024-10-22T02:05:24.215+0000] {task_command.py:467} INFO - Running <TaskInstance: auto_training_crawling_data_okx.crawl_data_task manual__2024-10-22T02:00:07.708586+00:00 [running]> on host ecs-gpu
[2024-10-22T02:05:24.293+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='auto_training_crawling_data_okx' AIRFLOW_CTX_TASK_ID='crawl_data_task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-22T02:00:07.708586+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-22T02:00:07.708586+00:00'
[2024-10-22T02:05:24.294+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-22T02:05:24.359+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/root/miniconda3/envs/project/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/root/miniconda3/envs/project/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/root/miniconda3/envs/project/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/root/miniconda3/envs/project/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/root/miniconda3/envs/project/lib/python3.8/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/root/miniconda3/envs/project/lib/python3.8/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/root/miniconda3/envs/project/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/root/airflow/dags/full_pipeline.py", line 226, in crawl_data
    current_time = datetime.now()
AttributeError: module 'datetime' has no attribute 'now'
[2024-10-22T02:05:24.365+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=auto_training_crawling_data_okx, task_id=crawl_data_task, run_id=manual__2024-10-22T02:00:07.708586+00:00, execution_date=20241022T020007, start_date=20241022T020524, end_date=20241022T020524
[2024-10-22T02:05:24.384+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-22T02:05:24.385+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 39 for task crawl_data_task (module 'datetime' has no attribute 'now'; 365263)
Traceback (most recent call last):
  File "/root/miniconda3/envs/project/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/root/miniconda3/envs/project/lib/python3.8/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/project/lib/python3.8/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/root/miniconda3/envs/project/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/root/miniconda3/envs/project/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/root/miniconda3/envs/project/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/root/miniconda3/envs/project/lib/python3.8/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/root/miniconda3/envs/project/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/root/miniconda3/envs/project/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/root/miniconda3/envs/project/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/root/miniconda3/envs/project/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/root/miniconda3/envs/project/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/root/miniconda3/envs/project/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/root/miniconda3/envs/project/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/root/miniconda3/envs/project/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/root/miniconda3/envs/project/lib/python3.8/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/root/miniconda3/envs/project/lib/python3.8/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/root/miniconda3/envs/project/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/root/airflow/dags/full_pipeline.py", line 226, in crawl_data
    current_time = datetime.now()
AttributeError: module 'datetime' has no attribute 'now'
[2024-10-22T02:05:24.404+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-22T02:05:24.432+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-22T02:05:24.443+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
